### ISSUE TITLE
Placeholder prefix missing for Firefox 19+

### ISSUE THREAD

**Issue by tommaton** [TryKickoff/trykickoff.github.io#9]
Hi Guy's,

I've been working with the placeholder mixin recently and noticed that the Firefox 19+ prefix was missing.

```
::-moz-placeholder { /* Firefox 19+ */
  color: $color;
}
```

**Comment by ashleynolan** [comment]
Is this not included by Autoprefixer when the CSS is compiled?

**Comment by tommaton** [comment]
I've checked and cant see any thing

**Comment by ashleynolan** [comment]
The mixin does contain the moz prefix in the latest version of Kickoff – [see this line](https://github.com/TryKickoff/kickoff/blob/master/assets/src/scss/mixins/_utility.scss#L89)

Although, this was a previous issue with Autoprefixer that has since been fixed – we shouldn’t need to use a mixin at all as Autoprefixer will add these prefixes automatically.

Will put this into he main Kickoff repo as an issue (as this is the Kickoff site repo) to update and test with Autoprefixer.
